service:
  name: aws-typescript-api
frameworkVersion: '>=1.72.0'
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local
provider:
  stage: dev
  region: ap-southeast-1
  name: aws
  runtime: nodejs12.x
  profile: serverless
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'
  versionFunctions: true
  variableSyntax: \${([^{}:]+?(?:\(|:)(?:[^:{}][^{}]*?)?)}
resources:
  Resources:
    Emails:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: emails
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
functions:
  getCityInfo:
    handler: lambdas/getCityInfo.handler
    events:
      - http:
          path: get-city/{city}
          method: get
          cors: true
    name: aws-typescript-api-dev-getCityInfo